# 
# b = 10000000
# Patient.create(:firstname => "KendraLoudDeloitte",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "LourdesBauswellOklahoma",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "HannahEdmisonM",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "TomLoezaSheraton",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "QueenieKramarczykGoeman",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "HuiPortaroA",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "JosefaOpitzNorman",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "LeaSteinhausJames",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "PaolaVielmaCongress",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "HortenciaBresserBatavia",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "LeannaTijerinaStephenson",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "DaniloPrideHarry",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "HueyMarcilleSouthern",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "ApoloniaWarneKitchen",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "ChandraLagosMeredith",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "CrissyPacholecCgi",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "GiannaBraninAll",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "ValentinBillaGeneral",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "IlonaDudashAdams",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "WillardLablancMershon",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "LaurynRandolJudy",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "LaurenaBeginBarry",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "EliseMichelleThurman",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "CorrieKardellLynch",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "KimberelyRabuseCarey",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "TishViolettElectro",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "HollisStanfieldFeehan",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "AndreeChristmannEaston",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "LylaFucilloHambro",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "FeltonYafusoPenkava",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "DellPolinoSaint",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "NohemiLekoBohne",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "TambraLembkeMoore",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "VickiMaikoksoongGeorge",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "RenatoAirhartSuper",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "LenitaDarbroBall",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "BarneyHagenFox",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "MatthewArmacostLivingston",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "BelenNeltonA",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "IeshaWardleHonker",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "FrancescoSarchetGabriel",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "PauleneRhuleBeck",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "CaroleHughlettKolodny",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "MissDunningMcgladrey",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "ElfriedaHinschY",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "EdelmiraCalzadoChagrin",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "JaimeWasurickLewis",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "LeraHuaYork",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "JameMastroJanney",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "JillianHailstoneGlobal",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "LouisZarlingDealers",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "EmmettMcshawYaffa",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "TammySamsPhotos",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "WillisWylieAcquired",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "MaximaBrzozowskiB",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "BorisLatifEmlou",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "SalinaKnavelSchiller",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "JustaDiniSuperior",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "AmaliaWolfgangKnutson",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "FelixTutterrowCorinth",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "EuraMcglocklinGraphic",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "LangHeuringHill",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "AgustinLakatosThrasher",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "JaimeLowranceSams",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "CarmanGudielWeiss",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "ArgeliaHofbauerMedical",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "MammieCisneyArellano",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "RashadMeninoWorld",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "JannaBastainHastings",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "CallieNeikirkShields",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "CoralHelmcampHepco",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "XeniaMusheroInstitute",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "AdelleNitcherJohn",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "HildegardeWehrweinOcean",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "PhuongSugaiScholtes",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "LeontineLafoyCaffrey",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "DarellMcalarneyJanney",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "MadonnaLandmanBrown",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "ChuckBerggrenWeyerhaeuser",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "GreggEpperheimerBest",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "YanBubrigDatabase",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "StephanieGarlettBrown",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "AlbertoStenquistDowell",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "WayneShiversRam",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "KristalBotheL",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "FlorenciaStadelCornwell",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "DarrinTumolilloMetro",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "FreemanRudigRamsey",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "LazaroMollisonUnited",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "EllsworthRiegPeyote",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "BrindaMrkvickaGittleman",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "FlorindaMackedanzHoyt",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "NadineSwartzbeckContact",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "ArletteTorchioA",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "AdolphKrivanecSas",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "GeorgianaColbathStewart",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "RanaLehnFreeman",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "ChiMorganHolmes",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "StarrProthroGs",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "GlennisRoseumYork",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "TheaPetermeierAnderson",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "RosalindPersechinoGrand",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "ShenikaTapianHelco",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "VetaVandebergRickard",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "HerschelGeneseoMolded",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "DianneTomasicSamios",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "MicahGertenFairfield",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "KayceeAlaibillaA",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "TeshaBrangButler",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "MaryaChhourAuchter",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))
# Patient.create(:firstname => "RonnieKettellePure",:lastname => Faker::Internet.user_name,:dob =>  Time.at(rand(999999400) + b))

# # Patient.createcreate(:firstname => ,:dob =:lastname => Faker::Internet.user_name,>  Time.at(rand(999999400) + b))


# typee = ["Administration", "Information", "Triage", "Triage"]

# for i in 1..250
#  length = (rand(18) + rand(0.9)).round(1)
# # sd = Time.at(rand(140000000) + 1319500000)
# Call.create(:calltype=> typee[rand 3]:patient_id => rand(111) , :length => length,:callerid => rand(20000000) + 964000)
# end
# # Time.at(rand(140000000) + 1319500000)


#Template 1

# ReportTemplateMaster.create(:template_name => "New_AfterHoursCallerListCST",:status => 1,:created_by => "admin",:updated_by=> "admin")

# ReportMaster.create(:report_name =>"New_AfterHoursCallerListCST",:status =>1,:report_template_master_id => 1,:created_by=> "admin",:updated_by=> "admin")
# ReportMaster.create(:report_name =>"New_AfterHoursCallerListCST_RemPatInfo",:status =>1,:report_template_master_id => 1,:created_by=> "admin",:updated_by=> "admin")
# ReportMaster.create(:report_name =>"New_CallCountByCallType",:status =>1,:report_template_master_id => 1,:created_by=> "admin",:updated_by=> "admin")

# ReportData.create(:report_master_id => 1,:column_name =>"callerid",:column_datatype => "Integer",:sequence => 1,:column_style=>"",:column_display_name => "callId")
# ReportData.create(:report_master_id => 1,:column_name =>"firstname",:column_datatype => "String",:sequence => 2,:column_style=>"",:column_display_name => "Name")
# ReportData.create(:report_master_id => 1,:column_name =>"dob",:column_datatype => "Date",:sequence => 3,:column_style=>"",:column_display_name => "DOB")
# ReportData.create(:report_master_id => 1,:column_name =>"CallReceivedCT",:column_datatype => "Datetime",:sequence => 4,:column_style=>"",:column_display_name => "Call Received CT")
# ReportData.create(:report_master_id => 1,:column_name =>"calltype",:column_datatype => "string",:sequence => 5,:column_style=>"",:column_display_name => "Call Type")



# ReportFilter.create(:report_master_id=> 1,:field_name => "callerid",:mandatory => 1)
# ReportFilter.create(:report_master_id=> 1,:field_name => "calltype",:mandatory => 1)
# ReportFilter.create(:report_master_id=> 2,:field_name => "length",:mandatory => 1)

# ReportFilter.create(:report_master_id=> 2,:field_name => "firstname",:mandatory => 1)
# ReportFilter.create(:report_master_id=> 2,:field_name => "lastname",:mandatory => 1)
# ReportFilter.create(:report_master_id=> 3,:field_name => "gender",:mandatory => 1)
# ReportFilter.create(:report_master_id=> 4,:field_name => "dob",:mandatory => 1)

    
# ReportHeader.create(:report_master_id => 1,:main_header => "After Hours Caller List (CST)",:header1 =>"Patient Information Excluded",:header2=> "17th and Chew - Lehigh Valley Physician Practice ~ ET",:header3=> "17th and Chew - Lehigh Valley Physician Practice",:repeat_header => 0)

# ReportSql.create(:status =>1,:report_master_id=>1,:created_by=>'admin')
# ReportSql.create(:status =>1,:report_master_id=>1,:created_by=>'admin')
# ReportSql.create(:status =>1,:report_master_id=>1,:created_by=>'admin')
    

# ReportHeader.create(:report_master_id => 1,:main_header => "After Hours Caller List (CST)")
# ReportHeader.create(:report_master_id => 1,:main_header => "After Hours Caller List (CST)")
# ReportHeader.create(:report_master_id => 1,:main_header => "After Hours Caller List (CST)")

ReportTemplateMaster.create(:html_content => "<div class='header-class'></div>")
ReportTemplateMaster.create(:html_content => "<div class='content-class'></div>")
ReportTemplateMaster.create(:html_content => "<div class='footer-content'></div>")
ReportTemplateMaster.create(:template_name => "headr1", :html_content => '<div><div>After Hours Caller List (CST)</div><br><div>17th and Chew - Lehigh Valley Physician Practice ~ ET</div><br><div style="">17th and Chew - Lehigh Valley Physician Practice</div></div>', :parent_id => 2 )

ReportTemplateMaster.create(:html_content => "<table></table>", :parent_id => 3)
ReportTemplateMaster.create(:html_content => "<tr></tr>", :parent_id => 6)
ReportTemplateMaster.create(:html_content => "<td></td>", :parent_id => 7)
ReportTemplateMaster.create(:html_content => "<th></th>", :parent_id => 7)